;;; pgmacs-chrome.el --- Additional icons and badges for PGmacs display  -*- lexical-binding: t; -*-

;; Copyright (C) 2025 Eric Marsden
;; Author: Eric Marsden <eric.marsden@risk-engineering.org>

(require 'svg)


(defun pgmacs--svg-icon-database ()
  "Return an SVG icon representing a database."
  (let ((icon (svg-create "1.3em" "1.3em" :viewBox "0 0 16 16")))
    (cl-flet ((ellipse (y)
                (svg-ellipse icon 8 y 5 1 :fill "purple")
                (svg-ellipse icon 8 (+ y 1.8) 5 1 :fill "purple" :stroke "white" :stroke-width 0.3)
                (svg-rectangle icon 3 y 10 1.5 :fill "purple")))
      (ellipse 9)
      (ellipse 6)
      (ellipse 3)
      (svg-image icon :margin 2 :ascent 'center))))

(defun pgmacs--svg-icon-user ()
  "Return an SVG icon representing a computer user."
  (let ((icon (svg-create "0.7em" "0.7em" :viewBox "0 0 16 16")))
    (svg-circle icon 8 4 3.8 :fill "black" :opacity 0.5)
    (svg-rectangle icon 1 9 15 20 :fill "black" :opacity 0.5 :rx 3)
    (svg-image icon :margin 2 :ascent 'center)))

(defun pgmacs--svg-icon-table ()
  "Return an SVG icon representing a database table."
  (let ((icon (svg-create "1em" "1em" :viewBox "-0.4 -0.4 3.6 4.6" :fill "currentColor")))
    (svg-rectangle icon 0 0 3 3 :fill "none" :stroke "black" :stroke-width 0.3 :rx 0.1)
    (svg-line icon 0 1 3 1 :stroke "black" :stroke-width 0.2)
    (svg-line icon 0 2 3 2 :stroke "black" :stroke-width 0.2)
    (svg-line icon 0 0.3 3 0.3 :stroke "black" :stroke-width 0.2)
    (svg-line icon 1 0 1 3 :stroke "black" :stroke-width 0.2)
    (svg-line icon 2 0 2 3 :stroke "black" :stroke-width 0.2)
    (svg-image icon :margin 2 :ascent 'center)))

(defun pgmacs--svg-icon-comment ()
  "Return an SVG icon representing a comment."
  (let* ((icon (svg-create "1em" "1em" :viewBox "0 0 32 32"))
         (d "M16 26c-1.168 0-2.296-.136-3.38-.367l-4.708 2.83.063-4.639C4.366 21.654 2 18.066 2 14 2 7.373 8.268 2 16 2s14 5.373 14 12c0 6.628-6.268 12-14 12Zm0-26C7.164 0 0 6.269 0 14c0 4.419 2.345 8.354 6 10.919V32l7.009-4.253c.97.16 1.968.253 2.991.253 8.836 0 16-6.268 16-14 0-7.731-7.164-14-16-14Zm7 11H9a1 1 0 0 0 0 2h14a1 1 0 1 0 0-2Zm-2 6H11a1 1 0 1 0 0 2h10a1 1 0 1 0 0-2Z"))
    (svg--append icon (dom-node 'path `((d . ,d) (fill . "#000") (fill-rule . "evenodd"))))
    (svg-image icon :margin (cons 5 3) :ascent 'center)))

(defun pgmacs--svg-icon-replication ()
  "Return an SVG icon representing data replication."
  (let* ((icon (svg-create "1em" "1em" :viewBox "0 0 32 32"))
         (d "M20 20v2h5.22a11.016 11.016 0 0 1-11.97 4.653l-.499 1.937A13 13 0 0 0 26 24.293V28h2v-8zm5-17a4.005 4.005 0 0 0-4 4a3.954 3.954 0 0 0 .567 2.019L9.019 21.567A3.952 3.952 0 0 0 7 21a4 4 0 1 0 4 4a3.954 3.954 0 0 0-.567-2.019l12.548-12.548A3.952 3.952 0 0 0 25 11a4 4 0 0 0 0-8M7 27a2 2 0 1 1 2-2a2.002 2.002 0 0 1-2 2M25 9a2 2 0 1 1 2-2a2.002 2.002 0 0 1-2 2m-9-6A13.04 13.04 0 0 0 6 7.707V4H4v8h8v-2H6.78a11.016 11.016 0 0 1 11.97-4.653l.499-1.937A13.036 13.036 0 0 0 16 3"))
    (svg--append icon (dom-node 'path `((d . ,d) (fill . "#000"))))
    (svg-image icon :margin (cons 3 1) :ascent 'center)))

(defun pgmacs--maybe-svg-icon (svg-fn)
  (if (and (display-graphic-p)
           (image-type-available-p 'svg))
      (let ((svg (funcall svg-fn)))
	(propertize " " 'display svg 'rear-nonsticky t 'cursor-intangible t))
    ""))


;; Return precalculated SVG badges for various fixed text items that we use when displaying
;; metainformation on tables and databases. The badges draw text and the border in the SVG
;; currentColor, which Emacs sets to the current foreground color. These badges are vectorized,
;; meaning that they contain no <text> elements, so they will not depend on the set of fonts
;; installed on the user's machine. (This is a weakness of the badges generated by the svg-lib
;; library.)
;;
;; The SVG must include an explicit height or width attribute; given the mechanism that Emacs uses
;; to determine the image's bounding box via librsvg, we can't use the :height and :width arguments
;; to make-image. We specify :height (which for a badge is fixed at "1em"), and the width is
;; determined automatically (as if we had specified width="auto" in the SVG).
;;
;; Why not generate these using Emacs' svg support? Unlike SVG rendering in a web browser, the
;; librsvg rendering used in Emacs does not provide access to text bounding boxes at runtime, so we
;; can't correctly draw the border of the badge independently of the set of fonts available. See the
;; poor aesthetics of the fallback result implemented below in pgmacs--make-badge/svg.
;;
;; Note: we could make use of the :css option to make-image with SVG images.
(defun pgmacs--lookup-badge (label)
  (pcase label
    ("SELECT"
     "<svg height=\"1em\" viewBox=\"-12.773 -50.391 209.37 65.93\" xmlns=\"http://www.w3.org/2000/svg\">
 <rect x=\"-9.7734\" y=\"-47.391\" width=\"203.37\" height=\"59.93\" rx=\"4\" ry=\"4\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"3\"/>
 <path transform=\"translate(0) scale(.023438 -.023438)\" d=\"m673-23c356 0 564 179 564 441 0 260-217 375-438 428l-139 36c-121 30-254 80-254 205 0 113 102 196 270 196 161 0 269-74 282-201h259c-7 249-219 428-537 428-312 0-544-176-544-439 0-210 147-336 396-400l169-44c161-42 269-91 269-207 0-128-123-215-299-215-168 0-301 76-313 233h-263c12-294 231-461 578-461z\" fill=\"currentColor\"/>
 <path transform=\"translate(31.219) scale(.023438 -.023438)\" d=\"m150 0h972v225h-705v416h649v222h-649v402h701v225h-968z\" fill=\"currentColor\"/>
 <path transform=\"translate(60.281) scale(.023438 -.023438)\" d=\"M150 0H1075V225H417V1490H150Z\" fill=\"currentColor\"/>
 <path transform=\"translate(87.422) scale(.023438 -.023438)\" d=\"m150 0h972v225h-705v416h649v222h-649v402h701v225h-968z\" fill=\"currentColor\"/>
 <path transform=\"translate(116.48) scale(.023438 -.023438)\" d=\"m785-20c352 0 588 231 629 516h-270c-34-176-178-277-356-277-242 0-417 183-417 525 0 338 174 527 418 527 178 0 322-101 355-277h269c-47 326-301 516-628 516-389 0-682-284-682-766 0-480 290-764 682-764z\" fill=\"currentColor\"/>
 <path transform=\"translate(151.85) scale(.023438 -.023438)\" d=\"M83 1265H543V0H810V1265H1269V1490H83Z\" fill=\"currentColor\"/>
</svg>")
    ("INSERT"
     "<svg height=\"1em\" viewBox=\"-11.484 -50.391 197.55 65.93\" xmlns=\"http://www.w3.org/2000/svg\">
     <rect x=\"-8.4844\" y=\"-47.391\" width=\"191.55\" height=\"59.93\" rx=\"4\" ry=\"4\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"3\"/>
     <path transform=\"translate(0) scale(.023438 -.023438)\" d=\"M417 1490H150V0H417Z\" fill=\"currentColor\"/>
     <path transform=\"translate(13.289) scale(.023438 -.023438)\" d=\"m150 0h272v740c0 83-9 240-19 424 100-194 156-300 234-425l465-739h303v1490h-271v-782c0-91 6-242 16-386-65 149-130 262-183 347l-515 821h-302z\" fill=\"currentColor\"/>
     <path transform=\"translate(49.734) scale(.023438 -.023438)\" d=\"m673-23c356 0 564 179 564 441 0 260-217 375-438 428l-139 36c-121 30-254 80-254 205 0 113 102 196 270 196 161 0 269-74 282-201h259c-7 249-219 428-537 428-312 0-544-176-544-439 0-210 147-336 396-400l169-44c161-42 269-91 269-207 0-128-123-215-299-215-168 0-301 76-313 233h-263c12-294 231-461 578-461z\" fill=\"currentColor\"/>
     <path transform=\"translate(80.953) scale(.023438 -.023438)\" d=\"m150 0h972v225h-705v416h649v222h-649v402h701v225h-968z\" fill=\"currentColor\"/>
     <path transform=\"translate(110.02) scale(.023438 -.023438)\" d=\"m150 0h267v547h278l293-547h299l-323 592c176 70 268 219 268 421 0 284-182 477-525 477h-557zm267 768v498h249c203 0 293-94 293-253 0-158-90-245-291-245z\" fill=\"currentColor\"/>
     <path transform=\"translate(141.33) scale(.023438 -.023438)\" d=\"M83 1265H543V0H810V1265H1269V1490H83Z\" fill=\"currentColor\"/>
     </svg>")
    ("UPDATE"
     "<svg height=\"1em\" viewBox=\"-11.484 -49.922 220.34 65.438\" xmlns=\"http://www.w3.org/2000/svg\">
 <rect x=\"-8.4844\" y=\"-46.922\" width=\"214.34\" height=\"59.438\" rx=\"4\" ry=\"4\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"3\"/>
 <path transform=\"translate(0) scale(.023438 -.023438)\" d=\"m754-22c363 0 604 220 604 539v973h-267v-951c0-187-131-322-337-322s-337 135-337 322v951h-267v-973c0-319 239-539 604-539z\" fill=\"currentColor\"/>
 <path transform=\"translate(35.32) scale(.023438 -.023438)\" d=\"m150 0h267v504h286c344 0 529 207 529 493 0 284-182 493-525 493h-557zm267 724v542h249c204 0 293-110 293-269s-89-273-291-273z\" fill=\"currentColor\"/>
 <path transform=\"translate(66.281) scale(.023438 -.023438)\" d=\"m654 0c454 0 721 281 721 747 0 463-267 743-711 743h-514v-1490zm-237 231v1028h231c305 0 464-171 464-512 0-344-159-516-471-516z\" fill=\"currentColor\"/>
 <path transform=\"translate(100.95) scale(.023438 -.023438)\" d=\"m50 0h292l122 369h557l127-369h293l-532 1490h-339zm485 584 63 190c41 133 86 300 139 508 55-206 102-371 146-508l65-190z\" fill=\"currentColor\"/>
 <path transform=\"translate(135.87) scale(.023438 -.023438)\" d=\"M83 1265H543V0H810V1265H1269V1490H83Z\" fill=\"currentColor\"/>
 <path transform=\"translate(167.55) scale(.023438 -.023438)\" d=\"m150 0h972v225h-705v416h649v222h-649v402h701v225h-968z\" fill=\"currentColor\"/>
</svg>")
    ("DELETE"
     "<svg height=\"1em\" baseProfile=\"tiny\" version=\"1.2\" viewBox=\"-11.484 -49.922 204.4 64.922\" xmlns=\"http://www.w3.org/2000/svg\">
 <rect x=\"-8.4844\" y=\"-46.922\" width=\"198.4\" height=\"58.922\" rx=\"4\" ry=\"4\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"3\"/>
 <path transform=\"translate(0) scale(.023438 -.023438)\" d=\"m654 0c454 0 721 281 721 747 0 463-267 743-711 743h-514v-1490zm-237 231v1028h231c305 0 464-171 464-512 0-344-159-516-471-516z\" fill=\"currentColor\"/>
 <path transform=\"translate(34.664) scale(.023438 -.023438)\" d=\"m150 0h972v225h-705v416h649v222h-649v402h701v225h-968z\" fill=\"currentColor\"/>
 <path transform=\"translate(63.727) scale(.023438 -.023438)\" d=\"M150 0H1075V225H417V1490H150Z\" fill=\"currentColor\"/>
 <path transform=\"translate(90.867) scale(.023438 -.023438)\" d=\"m150 0h972v225h-705v416h649v222h-649v402h701v225h-968z\" fill=\"currentColor\"/>
 <path transform=\"translate(119.93) scale(.023438 -.023438)\" d=\"M83 1265H543V0H810V1265H1269V1490H83Z\" fill=\"currentColor\"/>
 <path transform=\"translate(151.62) scale(.023438 -.023438)\" d=\"m150 0h972v225h-705v416h649v222h-649v402h701v225h-968z\" fill=\"currentColor\"/>
</svg>")
    ("TRUNCATE"
     "<svg height=\"1em\" baseProfile=\"tiny\" version=\"1.2\" viewBox=\"-13.055 -50.391 291.09 65.906\" xmlns=\"http://www.w3.org/2000/svg\">
 <rect x=\"-10.055\" y=\"-47.391\" width=\"285.09\" height=\"59.906\" rx=\"4\" ry=\"4\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"3\"/>
 <path transform=\"translate(0) scale(.023438 -.023438)\" d=\"M83 1265H543V0H810V1265H1269V1490H83Z\" fill=\"currentColor\"/>
 <path transform=\"translate(31.688) scale(.023438 -.023438)\" d=\"m150 0h267v547h278l293-547h299l-323 592c176 70 268 219 268 421 0 284-182 477-525 477h-557zm267 768v498h249c203 0 293-94 293-253 0-158-90-245-291-245z\" fill=\"currentColor\"/>
 <path transform=\"translate(63) scale(.023438 -.023438)\" d=\"m754-22c363 0 604 220 604 539v973h-267v-951c0-187-131-322-337-322s-337 135-337 322v951h-267v-973c0-319 239-539 604-539z\" fill=\"currentColor\"/>
 <path transform=\"translate(98.32) scale(.023438 -.023438)\" d=\"m150 0h272v740c0 83-9 240-19 424 100-194 156-300 234-425l465-739h303v1490h-271v-782c0-91 6-242 16-386-65 149-130 262-183 347l-515 821h-302z\" fill=\"currentColor\"/>
 <path transform=\"translate(134.77) scale(.023438 -.023438)\" d=\"m785-20c352 0 588 231 629 516h-270c-34-176-178-277-356-277-242 0-417 183-417 525 0 338 174 527 418 527 178 0 322-101 355-277h269c-47 326-301 516-628 516-389 0-682-284-682-766 0-480 290-764 682-764z\" fill=\"currentColor\"/>
 <path transform=\"translate(170.13) scale(.023438 -.023438)\" d=\"m50 0h292l122 369h557l127-369h293l-532 1490h-339zm485 584 63 190c41 133 86 300 139 508 55-206 102-371 146-508l65-190z\" fill=\"currentColor\"/>
 <path transform=\"translate(205.05) scale(.023438 -.023438)\" d=\"M83 1265H543V0H810V1265H1269V1490H83Z\" fill=\"currentColor\"/>
 <path transform=\"translate(236.74) scale(.023438 -.023438)\" d=\"m150 0h972v225h-705v416h649v222h-649v402h701v225h-968z\" fill=\"currentColor\"/>
</svg>")
    ("REFERENCES"
     "<svg height=\"1em\" viewBox=\"-11.484 -50.391 334.38 65.93\" xmlns=\"http://www.w3.org/2000/svg\">
 <rect x=\"-8.4844\" y=\"-47.391\" width=\"328.38\" height=\"59.93\" rx=\"4\" ry=\"4\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"3\"/>
 <path transform=\"translate(0) scale(.023438 -.023438)\" d=\"m150 0h267v547h278l293-547h299l-323 592c176 70 268 219 268 421 0 284-182 477-525 477h-557zm267 768v498h249c203 0 293-94 293-253 0-158-90-245-291-245z\" fill=\"currentColor\"/>
 <path transform=\"translate(31.312) scale(.023438 -.023438)\" d=\"m150 0h972v225h-705v416h649v222h-649v402h701v225h-968z\" fill=\"currentColor\"/>
 <path transform=\"translate(60.375) scale(.023438 -.023438)\" d=\"m150 0h267v596h620v222h-620v447h687v225h-954z\" fill=\"currentColor\"/>
 <path transform=\"translate(88.594) scale(.023438 -.023438)\" d=\"m150 0h972v225h-705v416h649v222h-649v402h701v225h-968z\" fill=\"currentColor\"/>
 <path transform=\"translate(117.66) scale(.023438 -.023438)\" d=\"m150 0h267v547h278l293-547h299l-323 592c176 70 268 219 268 421 0 284-182 477-525 477h-557zm267 768v498h249c203 0 293-94 293-253 0-158-90-245-291-245z\" fill=\"currentColor\"/>
 <path transform=\"translate(148.97) scale(.023438 -.023438)\" d=\"m150 0h972v225h-705v416h649v222h-649v402h701v225h-968z\" fill=\"currentColor\"/>
 <path transform=\"translate(178.03) scale(.023438 -.023438)\" d=\"m150 0h272v740c0 83-9 240-19 424 100-194 156-300 234-425l465-739h303v1490h-271v-782c0-91 6-242 16-386-65 149-130 262-183 347l-515 821h-302z\" fill=\"currentColor\"/>
 <path transform=\"translate(214.48) scale(.023438 -.023438)\" d=\"m785-20c352 0 588 231 629 516h-270c-34-176-178-277-356-277-242 0-417 183-417 525 0 338 174 527 418 527 178 0 322-101 355-277h269c-47 326-301 516-628 516-389 0-682-284-682-766 0-480 290-764 682-764z\" fill=\"currentColor\"/>
 <path transform=\"translate(249.84) scale(.023438 -.023438)\" d=\"m150 0h972v225h-705v416h649v222h-649v402h701v225h-968z\" fill=\"currentColor\"/>
 <path transform=\"translate(278.91) scale(.023438 -.023438)\" d=\"m673-23c356 0 564 179 564 441 0 260-217 375-438 428l-139 36c-121 30-254 80-254 205 0 113 102 196 270 196 161 0 269-74 282-201h259c-7 249-219 428-537 428-312 0-544-176-544-439 0-210 147-336 396-400l169-44c161-42 269-91 269-207 0-128-123-215-299-215-168 0-301 76-313 233h-263c12-294 231-461 578-461z\" fill=\"currentColor\"/>
</svg>")
    ("TRIGGER"
     "<svg height=\"1em\" viewBox=\"-13.055 -50.391 235.48 65.859\" xmlns=\"http://www.w3.org/2000/svg\">
 <rect x=\"-10.055\" y=\"-47.391\" width=\"229.48\" height=\"59.859\" rx=\"4\" ry=\"4\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"3\"/>
 <path transform=\"translate(0) scale(.023438 -.023438)\" d=\"M83 1265H543V0H810V1265H1269V1490H83Z\" fill=\"currentColor\"/>
 <path transform=\"translate(31.688) scale(.023438 -.023438)\" d=\"m150 0h267v547h278l293-547h299l-323 592c176 70 268 219 268 421 0 284-182 477-525 477h-557zm267 768v498h249c203 0 293-94 293-253 0-158-90-245-291-245z\" fill=\"currentColor\"/>
 <path transform=\"translate(63) scale(.023438 -.023438)\" d=\"M417 1490H150V0H417Z\" fill=\"currentColor\"/>
 <path transform=\"translate(76.289) scale(.023438 -.023438)\" d=\"m793-20c368 0 632 237 632 620v179h-603v-210h344c-5-214-148-350-372-350-251 0-423 189-423 526 0 338 176 526 417 526 181 0 303-98 351-257h273c-46 293-299 496-627 496-390 0-682-287-682-767 0-471 279-763 690-763z\" fill=\"currentColor\"/>
 <path transform=\"translate(112.24) scale(.023438 -.023438)\" d=\"m793-20c368 0 632 237 632 620v179h-603v-210h344c-5-214-148-350-372-350-251 0-423 189-423 526 0 338 176 526 417 526 181 0 303-98 351-257h273c-46 293-299 496-627 496-390 0-682-287-682-767 0-471 279-763 690-763z\" fill=\"currentColor\"/>
 <path transform=\"translate(148.2) scale(.023438 -.023438)\" d=\"m150 0h972v225h-705v416h649v222h-649v402h701v225h-968z\" fill=\"currentColor\"/>
 <path transform=\"translate(177.26) scale(.023438 -.023438)\" d=\"m150 0h267v547h278l293-547h299l-323 592c176 70 268 219 268 421 0 284-182 477-525 477h-557zm267 768v498h249c203 0 293-94 293-253 0-158-90-245-291-245z\" fill=\"currentColor\"/>
</svg>")
    ("MAINTAIN"
     "<svg height=\"1em\" viewBox=\"-11.484 -49.922 268.24 64.922\" xmlns=\"http://www.w3.org/2000/svg\">
 <rect x=\"-8.4844\" y=\"-46.922\" width=\"262.24\" height=\"58.922\" rx=\"4\" ry=\"4\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"3\"/>
 <path transform=\"translate(0) scale(.023438 -.023438)\" d=\"m150 0h262v752c0 113-6 319-10 488 55-192 115-391 150-488l279-752h227l275 752c35 100 98 305 149 496-3-177-9-385-9-496v-752h266v1490h-403l-280-769c-29-89-75-273-110-420-34 149-81 332-111 420l-283 769h-402z\" fill=\"currentColor\"/>
 <path transform=\"translate(44.273) scale(.023438 -.023438)\" d=\"m50 0h292l122 369h557l127-369h293l-532 1490h-339zm485 584 63 190c41 133 86 300 139 508 55-206 102-371 146-508l65-190z\" fill=\"currentColor\"/>
 <path transform=\"translate(79.195) scale(.023438 -.023438)\" d=\"M417 1490H150V0H417Z\" fill=\"currentColor\"/>
 <path transform=\"translate(92.484) scale(.023438 -.023438)\" d=\"m150 0h272v740c0 83-9 240-19 424 100-194 156-300 234-425l465-739h303v1490h-271v-782c0-91 6-242 16-386-65 149-130 262-183 347l-515 821h-302z\" fill=\"currentColor\"/>
 <path transform=\"translate(128.93) scale(.023438 -.023438)\" d=\"M83 1265H543V0H810V1265H1269V1490H83Z\" fill=\"currentColor\"/>
 <path transform=\"translate(160.62) scale(.023438 -.023438)\" d=\"m50 0h292l122 369h557l127-369h293l-532 1490h-339zm485 584 63 190c41 133 86 300 139 508 55-206 102-371 146-508l65-190z\" fill=\"currentColor\"/>
 <path transform=\"translate(195.54) scale(.023438 -.023438)\" d=\"M417 1490H150V0H417Z\" fill=\"currentColor\"/>
 <path transform=\"translate(208.83) scale(.023438 -.023438)\" d=\"m150 0h272v740c0 83-9 240-19 424 100-194 156-300 234-425l465-739h303v1490h-271v-782c0-91 6-242 16-386-65 149-130 262-183 347l-515 821h-302z\" fill=\"currentColor\"/>
</svg>")
    ("NOT NULL"
     "<svg height=\"1em\" viewBox=\"-11.484 -50.391 255.61 65.906\" xmlns=\"http://www.w3.org/2000/svg\">
 <rect x=\"-8.4844\" y=\"-47.391\" width=\"249.61\" height=\"59.906\" rx=\"4\" ry=\"4\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"3\"/>
 <path transform=\"translate(0) scale(.023438 -.023438)\" d=\"m150 0h272v740c0 83-9 240-19 424 100-194 156-300 234-425l465-739h303v1490h-271v-782c0-91 6-242 16-386-65 149-130 262-183 347l-515 821h-302z\" fill=\"currentColor\"/>
 <path transform=\"translate(36.445) scale(.023438 -.023438)\" d=\"m788-20c390 0 683 283 683 764 0 482-293 766-683 766-391 0-685-284-685-766 0-480 294-764 685-764zm0 239c-244 0-417 186-417 525 0 341 173 527 417 527 242 0 414-185 414-527 0-340-172-525-414-525z\" fill=\"currentColor\"/>
 <path transform=\"translate(73.336) scale(.023438 -.023438)\" d=\"M83 1265H543V0H810V1265H1269V1490H83Z\" fill=\"currentColor\"/>
 <path transform=\"translate(105.02) scale(.023438 -.023438)\" d=\"m150 0h272v740c0 83-9 240-19 424 100-194 156-300 234-425l465-739h303v1490h-271v-782c0-91 6-242 16-386-65 149-130 262-183 347l-515 821h-302z\" fill=\"currentColor\"/>
 <path transform=\"translate(141.47) scale(.023438 -.023438)\" d=\"m754-22c363 0 604 220 604 539v973h-267v-951c0-187-131-322-337-322s-337 135-337 322v951h-267v-973c0-319 239-539 604-539z\" fill=\"currentColor\"/>
 <path transform=\"translate(176.79) scale(.023438 -.023438)\" d=\"M150 0H1075V225H417V1490H150Z\" fill=\"currentColor\"/>
 <path transform=\"translate(203.93) scale(.023438 -.023438)\" d=\"M150 0H1075V225H417V1490H150Z\" fill=\"currentColor\"/>
</svg>")
    ("PRIMARY KEY"
     "<svg height=\"1em\" viewBox=\"-11.484 -49.922 342.68 64.922\" xmlns=\"http://www.w3.org/2000/svg\">
 <rect x=\"-8.4844\" y=\"-46.922\" width=\"336.68\" height=\"58.922\" rx=\"4\" ry=\"4\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"3\"/>
 <path transform=\"translate(0) scale(.023438 -.023438)\" d=\"m150 0h267v504h286c344 0 529 207 529 493 0 284-182 493-525 493h-557zm267 724v542h249c204 0 293-110 293-269s-89-273-291-273z\" fill=\"currentColor\"/>
 <path transform=\"translate(30.961) scale(.023438 -.023438)\" d=\"m150 0h267v547h278l293-547h299l-323 592c176 70 268 219 268 421 0 284-182 477-525 477h-557zm267 768v498h249c203 0 293-94 293-253 0-158-90-245-291-245z\" fill=\"currentColor\"/>
 <path transform=\"translate(62.273) scale(.023438 -.023438)\" d=\"M417 1490H150V0H417Z\" fill=\"currentColor\"/>
 <path transform=\"translate(75.562) scale(.023438 -.023438)\" d=\"m150 0h262v752c0 113-6 319-10 488 55-192 115-391 150-488l279-752h227l275 752c35 100 98 305 149 496-3-177-9-385-9-496v-752h266v1490h-403l-280-769c-29-89-75-273-110-420-34 149-81 332-111 420l-283 769h-402z\" fill=\"currentColor\"/>
 <path transform=\"translate(119.84) scale(.023438 -.023438)\" d=\"m50 0h292l122 369h557l127-369h293l-532 1490h-339zm485 584 63 190c41 133 86 300 139 508 55-206 102-371 146-508l65-190z\" fill=\"currentColor\"/>
 <path transform=\"translate(154.76) scale(.023438 -.023438)\" d=\"m150 0h267v547h278l293-547h299l-323 592c176 70 268 219 268 421 0 284-182 477-525 477h-557zm267 768v498h249c203 0 293-94 293-253 0-158-90-245-291-245z\" fill=\"currentColor\"/>
 <path transform=\"translate(186.07) scale(.023438 -.023438)\" d=\"m600 0h267v577l544 913h-310l-261-470c-39-71-72-135-105-220-33 83-66 147-107 220l-266 470h-312l550-913z\" fill=\"currentColor\"/>
 <path transform=\"translate(220.31) scale(.023438 -.023438)\" d=\"m150 0h267v447l203 221 452-668h315l-582 845 572 645h-332l-391-446c-98-114-171-208-241-315l4 319v442h-267z\" fill=\"currentColor\"/>
 <path transform=\"translate(254.06) scale(.023438 -.023438)\" d=\"m150 0h972v225h-705v416h649v222h-649v402h701v225h-968z\" fill=\"currentColor\"/>
 <path transform=\"translate(283.12) scale(.023438 -.023438)\" d=\"m600 0h267v577l544 913h-310l-261-470c-39-71-72-135-105-220-33 83-66 147-107 220l-266 470h-312l550-913z\" fill=\"currentColor\"/>
</svg>")
    ("DEFAULT"
     "<svg height=\"1em\" viewBox=\"-11.484 -49.922 245.55 65.438\" xmlns=\"http://www.w3.org/2000/svg\">
 <rect x=\"-8.4844\" y=\"-46.922\" width=\"239.55\" height=\"59.438\" rx=\"4\" ry=\"4\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"3\"/>
 <path transform=\"translate(0) scale(.023438 -.023438)\" d=\"m654 0c454 0 721 281 721 747 0 463-267 743-711 743h-514v-1490zm-237 231v1028h231c305 0 464-171 464-512 0-344-159-516-471-516z\" fill=\"currentColor\"/>
 <path transform=\"translate(34.664) scale(.023438 -.023438)\" d=\"m150 0h972v225h-705v416h649v222h-649v402h701v225h-968z\" fill=\"currentColor\"/>
 <path transform=\"translate(63.727) scale(.023438 -.023438)\" d=\"m150 0h267v596h620v222h-620v447h687v225h-954z\" fill=\"currentColor\"/>
 <path transform=\"translate(91.945) scale(.023438 -.023438)\" d=\"m50 0h292l122 369h557l127-369h293l-532 1490h-339zm485 584 63 190c41 133 86 300 139 508 55-206 102-371 146-508l65-190z\" fill=\"currentColor\"/>
 <path transform=\"translate(126.87) scale(.023438 -.023438)\" d=\"m754-22c363 0 604 220 604 539v973h-267v-951c0-187-131-322-337-322s-337 135-337 322v951h-267v-973c0-319 239-539 604-539z\" fill=\"currentColor\"/>
 <path transform=\"translate(162.19) scale(.023438 -.023438)\" d=\"M150 0H1075V225H417V1490H150Z\" fill=\"currentColor\"/>
 <path transform=\"translate(189.33) scale(.023438 -.023438)\" d=\"M83 1265H543V0H810V1265H1269V1490H83Z\" fill=\"currentColor\"/>
</svg>")
    ("CHECK"
     "<svg height=\"1em\" viewBox=\"-12.586 -50.391 195.68 65.859\" xmlns=\"http://www.w3.org/2000/svg\">
 <rect x=\"-9.5859\" y=\"-47.391\" width=\"189.68\" height=\"59.859\" rx=\"4\" ry=\"4\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"3\"/>
 <path transform=\"translate(0) scale(.023438 -.023438)\" d=\"m785-20c352 0 588 231 629 516h-270c-34-176-178-277-356-277-242 0-417 183-417 525 0 338 174 527 418 527 178 0 322-101 355-277h269c-47 326-301 516-628 516-389 0-682-284-682-766 0-480 290-764 682-764z\" fill=\"currentColor\"/>
 <path transform=\"translate(35.367) scale(.023438 -.023438)\" d=\"M150 0H417V649H1110V0H1377V1490H1110V874H417V1490H150Z\" fill=\"currentColor\"/>
 <path transform=\"translate(71.156) scale(.023438 -.023438)\" d=\"m150 0h972v225h-705v416h649v222h-649v402h701v225h-968z\" fill=\"currentColor\"/>
 <path transform=\"translate(100.22) scale(.023438 -.023438)\" d=\"m785-20c352 0 588 231 629 516h-270c-34-176-178-277-356-277-242 0-417 183-417 525 0 338 174 527 418 527 178 0 322-101 355-277h269c-47 326-301 516-628 516-389 0-682-284-682-766 0-480 290-764 682-764z\" fill=\"currentColor\"/>
 <path transform=\"translate(135.59) scale(.023438 -.023438)\" d=\"m150 0h267v447l203 221 452-668h315l-582 845 572 645h-332l-391-446c-98-114-171-208-241-315l4 319v442h-267z\" fill=\"currentColor\"/>
</svg>")))

(cl-defun pgmacs--make-badge/svg (label &key color)
  (when-let ((svg (pgmacs--lookup-badge label)))
    (cl-return-from pgmacs--make-badge/svg
      (create-image svg 'svg t :margin 1 :ascent 'center :foreground color)))
  (let* ((width (* 0.9 (string-pixel-width label)))
         (height (+ (window-font-height) 2))
         (badge (svg-create (format "%fpx" width) "1em"
                            :viewBox (format "0 0 %f %d" width height))))
    (svg-rectangle badge (* 0.01 width) (* 0.01 height) (* 0.99 width) (* 0.99 height)
                   :fill "none"
                   :stroke-color color
                   :stroke-width 0.3
                   :rx 1.9)
    (svg-text badge label :x (* 0.05 width) :y (* 0.65 height)
              :text-anchor "left"
              :font-stretch 'condensed
              :stroke color
              :padding 2
              :font-family "Inter,Helvetica"
              :font-weight 300
              :font-size "10px")
    (svg-image badge :margin 1 :ascent 'center)))

(cl-defun pgmacs--make-badge/text (label &key color help-echo)
  (propertize label 'face `((background-color . ,color) (height . 0.7) (raise 0.1) (:box t)) 'help-echo help-echo))

(cl-defun pgmacs--make-badge (label &key color help-echo)
  (if (and (display-graphic-p)
           (image-type-available-p 'svg))
      (let ((svg (pgmacs--make-badge/svg label :color color)))
        (propertize " " 'display svg 'rear-nonsticky t 'cursor-intangible t 'help-echo help-echo))
    (pgmacs--make-badge/text label :color color :help-echo help-echo)))

(provide 'pgmacs-chrome)

;; pgmacs-chrome.el ends here
