#        -*- Dockerfile -*-
#
# Recipe to build a container image including a terminal-only Emacs, PGmacs and its dependencies.
# Container size is 150MB on AMD64.
#
# To build the container locally (not needed for an end user):
#
#    podman build -f etc/Containerfile --tag pgmacs .
#
# To run the container:
#
#    podman run --net host -ti localhost/pgmacs


FROM docker.io/alpine:latest as builder
LABEL stage=builder
WORKDIR /src
RUN apk update && \
    apk upgrade && \
    apk add --no-cache git && \
    wget -q -O peg.el "https://git.savannah.gnu.org/cgit/emacs/elpa.git/plain/peg.el?h=externals/peg" && \
    wget -q -O csv-mode.el "https://git.savannah.gnu.org/cgit/emacs/elpa.git/plain/csv-mode.el?h=externals/csv-mode" && \
    git clone --depth 1 https://github.com/emarsden/pg-el.git && \
    git clone --depth 1 https://github.com/emarsden/pgmacs.git


FROM docker.io/alpine:latest
LABEL org.opencontainers.image.description "The Emacs-based browser/editor for PostgreSQL."
LABEL org.opencontainers.image.title "PGmacs"
LABEL org.opencontainers.image.url "https://github.com/emarsden/pgmacs"
LABEL org.opencontainers.image.source "https://github.com/emarsden/pgmacs"
LABEL org.opencontainers.image.version "0.9"
LABEL org.opencontainers.image.authors "eric.marsden@risk-engineering.org"
LABEL org.opencontainers.image.licenses "GPLv2"

RUN apk update && \
    apk upgrade && \
    apk add --no-cache emacs-nox ncurses && \
    mkdir /elisp && \
    chown root.root /elisp && \
    chmod a=rwx,o+t /elisp && \
    ls -l /usr/share/emacs/site-lisp && \
    echo "(push \"/elisp\" load-path)" > /usr/share/emacs/site-lisp/site-start.el && \
    echo "(require 'pgmacs)" >> /usr/share/emacs/site-lisp/site-start.el 

COPY --from=builder --chown=root:root /src/peg.el /elisp
COPY --from=builder --chown=root:root /src/csv-mode.el /elisp
COPY --from=builder --chown=root:root /src/pg-el/pg.el /elisp
COPY --from=builder --chown=root:root /src/pg-el/pg-geometry.el /elisp
COPY --from=builder --chown=root:root /src/pg-el/pg-lo.el /elisp
COPY --from=builder --chown=root:root /src/pgmacs/pgmacstbl.el /elisp
COPY --from=builder --chown=root:root /src/pgmacs/pgmacs.el /elisp

WORKDIR /app
ENV TERM=xterm-256color
ENTRYPOINT ["/usr/bin/emacs", "-f", "pgmacs"]


